Dev
manualcheg/Playlist_maker pull request #9
Opened 2023-05-09 19:20 UTC by manualcheg

Спринт 14
Реализован функционал аудиоплеера
Реализован поиск с задержкой без нажатия кнопок
Добавление ProgressBar при API-запросах
Перевод запросов к itunes на http

2023-05-11 16:14 UTC, NoDopezzz requested changes

2023-05-11 16:14 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +    private var mainThreadHandler: Handler? = null
⏫ `mainThreadHandler` можно инициализировать сразу при создании класса. `Handler` и `Looper` не зависят от жизненного цикла какого-либо экрана и доступны в любой части приложения

2023-05-11 16:14 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +        val previewUrl = intent.getStringExtra("previewUrl")
⏫ Обычно, когда возникает необходимость передавать некий объект через `Intent`, сохранять объект в `onSavedInstanceState` или сохранять объект в аргументах `Fragment`'ов (про фрагменты будет рассказано в следующих спринтах) андроид использует `Bundle` для сохранения и передачи данных. Особенность `Bundle` заключается в том, что он представляет собой коллекцию пар *"ключ-значение"*, где ключи являются строками, а значения могут быть различных типов данных, таких как строки, числа, а также объекты классов `Parcelable` и `Serializable`, то есть сериализуемые объекты.

В Android существует несколько способов сериализации объектов:
`Serializable`, `Parcelable`, `JSON`.

В угоду масштабируемости и гибкости гораздо лучше воспользоваться одним из этих способ сериализации объектов, чем передавать поля по-отдельности.

2023-05-11 16:14 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +        val startOfDataExpression = 0
⏫ Лучше эти значения вынести в константы - `const val` внутри `companion object`

2023-05-11 16:14 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +                playbackControl()
⏫ Нет необходимости для `playbackControl()` создавать объект Thread и вызывать в отдельном потоке.

2023-05-11 16:14 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +    }
⏫ В названии константных переменных, лучше указывать название величины. В данном случае `PLAYBACK_TIME_RENEW_DELAY_MS`

2023-05-11 16:14 UTC, NoDopezzz commented on app/src/main/res/drawable/image_pause_button.xml
> +      android:fillColor="#1A1B22"/>
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в `drawable`, а файл ресурса с цветом будет задан в `values` и `values-night`

2023-05-11 16:14 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/TrackItemAdapter.kt
>              intent.putExtra("releaseDate",track.releaseDate)
⚠️ Не был добавлен функционал `debounce'а` при нажатии на элемент трека. 
Советую также вынести обработку нажатия в `Activity`, чтобы иметь флаг для дебаунса общий для всех элементов

2023-05-14 14:11 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +    private var mainThreadHandler: Handler? = null
Понял. Спасибо! 
Сделал

2023-05-14 20:42 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +        val previewUrl = intent.getStringExtra("previewUrl")
Передал объект в интент через сериализацию Gson().
Спасибо!

2023-05-14 20:54 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +        val startOfDataExpression = 0
OK

2023-05-14 20:57 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +                playbackControl()
Уже понял это, перечитав часть теории про MediaPlayer. Это была попытка предотвратить постоянный рестарт прокрутки имени исполнителя и названия трека.
Убрал.

2023-05-14 21:04 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/PlayerActivity.kt
> +    }
Изменил. Постараюсь запомнить.

2023-05-14 21:05 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/TrackItemAdapter.kt
>              intent.putExtra("releaseDate",track.releaseDate)
Проглядел.
Добавил.

2023-05-15 11:36 UTC, manualcheg commented on app/src/main/res/drawable/image_pause_button.xml
> +      android:fillColor="#1A1B22"/>
Понял. У кнопки Play сделал так.
У кнопки Pause уже была такая реализация, но через цвет светлой/темной тем.

2023-05-15 11:56 UTC, manualcheg commented on app/src/main/java/com/practicum/playlistmaker/TrackItemAdapter.kt
>              intent.putExtra("releaseDate",track.releaseDate)
Только как вынести обработку нажатия, увы, не знаю.

2023-05-16 11:49 UTC, NoDopezzz approved these changes

2023-05-19 17:21 UTC, merged